# Generated by Django 4.0.4 on 2022-05-16 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testeWS', '0002_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ano', models.IntegerField()),
                ('combustivel', models.CharField(choices=[('F', 'Flex'), ('A', 'Alcool'), ('G', 'Gasolina')], default='G', max_length=1)),
                ('num_portas', models.CharField(choices=[('2', 'Duas Portas'), ('4', 'Quatro Portas')], default='4', max_length=1)),
                ('cor', models.CharField(max_length=30)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testeWS.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testeWS.modelo')),
            ],
        ),
    ]
