# Generated by Django 4.0.4 on 2022-05-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testeWS', '0003_carro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='marca',
            new_name='marca_id',
        ),
    ]
