# Generated by Django 4.0.4 on 2022-05-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeWS', '0005_alter_carro_timestamp_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='timestamp_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
